name: create-comment

on:
    issues: 
      types: [opened]


jobs:
    comment-with-action:
        runs-on: ubuntu-latest
        steps:
            - name: I don't know what is this
              run: echo 's{{ toJSON(github.event) }}' | jq
              shell: bash               
